import './jqui.js';
import './jqfp.js';
import ManageObj from './Manage.js';
  ManageObj
            .init('wrapper')
                .addPage('index')
                    .addComponent({
                        width:428,
                        height :92,
                        center:true,
                        css:{
                            position:'absolute',
                            top:-10,
                            opacity:0,
                            backgroundImage:'url(./src/img/logoIndex.png)'
                        },
                        animateIn:{
                            top:100,
                            opacity:1
                        },
                        animateOut:{
                            top:-10,
                            opacity:0
                        },
                        delay:200
                    })
                      .addComponent({
                        name:'shake',
                        width:370,
                        height :96,
                        center:true,
                        css:{
                            position:'absolute',
                            top:220,
                            left:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/slogan.png)'
                        },
                        animateIn:{
                            left:'50%',
                            opacity:1
                        },
                        animateOut:{
                            left:0,
                            opacity:0
                        },
                        delay:800
                    })
                     .addComponent({
                        width:346,
                        height :494,
                        css:{
                            position:'absolute',
                            bottom:-20,
                            left:-20,
                            opacity:0,
                            backgroundImage:'url(./src/img/left.png)'
                        },
                        animateIn:{
                            left:0,
                            bottom:0,
                            opacity:1
                        },
                        animateOut:{
                             bottom:-20,
                            left:-20,
                            opacity:0
                        },
                        delay:1200
                    })
                    .addComponent({
                        width:324,
                        height :450,
                        css:{
                            position:'absolute',
                            bottom:-20,
                            right:-20,
                            opacity:0,
                            backgroundImage:'url(./src/img/right.png)'
                        },
                        animateIn:{
                            right:0,
                            bottom:0,
                            opacity:1
                        },
                        animateOut:{
                             bottom:-20,
                            right:-20,
                            opacity:0
                        },
                        delay:1600
                    })
                .addPage()
                     .addComponent({
                        width:500,
                        height :124,
                        css:{
                            position:'absolute',
                            top:0,

                            opacity:0,
                            backgroundImage:'url(./src/img/mind.png)'
                        },
                        animateIn:{
                            top:60,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:200
                    })
                     .addComponent({
                        width:500,
                        height :50,
                        center:true,
                        text:'用实力让情怀落地！',
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            lineHeight:'25px',
                            fontSize:'25px',
                            textAlign:'center',
                            fontWeight:'900',
                            color:'#f40'
                        },
                        animateIn:{
                            top:150,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:600
                    })
                     .addComponent({
                        width:522,
                        height :300,
                        text:'渡一教育创立于2015年！在成哥 邓哥 彤哥的带领下向着高端编程教育公司大踏步，渡一 Dream Factory，渡一Web Coffee 于今年成立',
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/dialog.png)',
                            padding:'10px 10px 10px 10px',
                            textAlign:'justify',
                            fontSize:'18px',
                            lineHeight:'25px',
                            fontWeight:'900'
                        },
                        animateIn:{
                            bottom:240,
                            opacity:1
                        },
                        animateOut:{
                            bottom:0,
                            opacity:0
                        },
                        delay:1100
                    })
                     .addComponent({
                        width:516,
                        height :306,
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:-10,
                            opacity:0,
                            backgroundImage:'url(./src/img/people.png)'
                        },
                        animateIn:{
                            bottom:20,
                            opacity:1
                        },
                        animateOut:{
                            bottom:-10,
                            opacity:0
                        },
                        delay:1500
                    })
                .addPage()
                     .addComponent({
                        width:500,
                        height: 124,
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/bar.png)'
                        },
                        animateIn:{
                            top:60,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:200
                    })
                     .addComponent({
                        width:428,
                        height :92,
                        center:true,
                        text:'课程体系柱状图',
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            lineHeight:'25px',
                            textAlign:'center',
                            fontWeight:900,
                            fontSize:'25px',
                            color:'#f40'
                        },
                        animateIn:{
                            top:200,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:600
                    })
                     .addComponent({
                         type:'Bar',
                        width:500,
                        height :300,
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:0,
                            opacity:0,
                            fontWeight:900
                        },
                        animateIn:{
                            bottom:200,
                            opacity:1
                        },
                        animateOut:{
                            bottom:0,
                            opacity:0
                        },
                          data:[
                        ['js',0.3,'red'],
                        ['html',0.1,'blue'],
                        ['css3',0.2,'pink'],
                        ['jquery',0.2,'green'],
                        ['react',0.2,'black']
                        ],
                        delay:1000
                    })
                .addPage()
                     .addComponent({
                        width:500,
                        height: 126,
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/poyline.png)'
                        },
                        animateIn:{
                            top:60,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:200
                    })
                     .addComponent({
                        width:428,
                        height :92,
                        center:true,
                        text:'课程体系折线图',
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            lineHeight:'25px',
                            textAlign:'center',
                            fontWeight:900,
                            fontSize:'25px',
                            color:'#f40'
                        },
                        animateIn:{
                            top:200,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:600
                    })
                     .addComponent({
                         type:'Poly',
                        width:500,
                        height :500,
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:0,
                            opacity:0,
                            fontWeight:900
                        },
                        animateIn:{
                            bottom:100,
                            opacity:1
                        },
                        animateOut:{
                            bottom:0,
                            opacity:0
                        },
                          data:[
                        ['js',0.3,'red'],
                        ['html',0.1,'blue'],
                        ['css3',0.2,'pink'],
                        ['jq',0.3,'green'],
                        ['react',0.1,'black']
                        ],
                        delay:1000
                    })
                .addPage()
                    .addComponent({
                        width:500,
                        height: 126,
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/pie.png)'
                        },
                        animateIn:{
                            top:60,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:200
                    })
                     .addComponent({
                        width:428,
                        height :92,
                        center:true,
                        text:'课程体系饼图',
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            lineHeight:'25px',
                            textAlign:'center',
                            fontWeight:900,
                            fontSize:'25px',
                            color:'#f40'
                        },
                        animateIn:{
                            top:200,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:600
                    })
                     .addComponent({
                         type:'pie',
                        width:500,
                        height :500,
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:0,
                            opacity:0,
                            fontWeight:900
                        },
                        animateIn:{
                            bottom:100,
                            opacity:1
                        },
                        animateOut:{
                            bottom:0,
                            opacity:0
                        },
                          data:[
                        ['js',0.3,'red'],
                        ['html',0.1,'blue'],
                        ['css3',0.2,'pink'],
                        ['jq',0.3,'green'],
                        ['react',0.1,'yellow']
                        ],
                        delay:1000
                    })
                .addPage()
                    .addComponent({
                        name:'back',
                        width:48,
                        height :26,
                        center:true,
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/back.png)'
                        },
                        animateIn:{
                            top:30,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        event:{
                            click:()=>{
                                ManageObj.oContainer.fullpage.moveTo(1);
                            }
                        },
                        delay:200
                    })
                    .addComponent({
                        width:128,
                        height :120,
                        css:{
                            position:'absolute',
                            top:100,
                            right:50,
                            opacity:0,
                            backgroundImage:'url(./src/img/share.png)'
                        },
                        animateIn:{
                            top:0,
                            right:0,
                            opacity:1
                        },
                        animateOut:{
                            top:100,
                            right:50,
                            opacity:0
                        },
                        delay:600
                    })
                    .addComponent({
                        name:'shake',
                        width:428,
                        height :92,
                        center:true,
                        css:{
                            position:'absolute',
                            top:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/logo.png)'
                        },
                        animateIn:{
                            top:250,
                            opacity:1
                        },
                        animateOut:{
                            top:0,
                            opacity:0
                        },
                        delay:1000
                    })
                    .addComponent({
                        width:370,
                        height :96,
                        center:true,
                        css:{
                            position:'absolute',
                            bottom:200,
                            left:0,
                            opacity:0,
                            backgroundImage:'url(./src/img/slogan.png)'
                        },
                        animateIn:{
                            left:'50%',
                            opacity:1
                        },
                        animateOut:{
                            left:0,
                            opacity:0
                        },
                        delay:800
                    })
            .load();